apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sandbox-system
configMapGenerator:
  - name: sandbox-egress-profiles
    files:
      - profiles.yaml
generatorOptions:
  disableNameSuffixHash: true
